### ISSUE TITLE
MVP Features

### ISSUE THREAD

**Issue by minasmart** [Shopify/graphql-js-client#13]
# Tasks
## Refetch / Next page
- [x] Rename graph to `Query`, which is part of a `Document`
- [ ] Maybe separate relay assumptions...? (`Document` & `RelayDocument`?
- [ ] Pruning to nearest Node.
  - [ ] Find nearest node
- [ ] Pruning to this graph is a Node.
  - [ ] `graph.type.isNode`
- [ ] Will require `graph.dup()`
  
  Duplicates this graph instance. Not parents or children. Means
  restructuring won't actually have side effects on an existing query
  structure.
- [x] Will require the ability to add a sub graph through `addField`
- [x] Support interfaces in `graphql-js-schema
- [ ] Add to args (at least for connections: `cursor`, `after`)
- [x] Arguments with variables eg. `input: $input`
- [ ] Will require pairing the query graph to the deserialized graph
- [ ] Some sane way to have as a default on queries.

``` graphql
query {
  ... on Node {
    id
  }
}
```
## Named Fragments and references
- [ ] complete? subtasks?
## Named Documents
- [ ] contains queries
- [ ] contains mutations
## Mutations
- [ ] complete? subtasks?
## Parity in CLI lints and generated lints
- [ ] complete? subtasks?

**Inspiration from [graphq-ruby-client](https://github.com/Shopify/graphql-ruby-client/tree/master/test/graphql_client/query)**
## Unions
- [ ] figure out what we need to do to support unions
